name: home
description: "A new Flutter package project."
version: 0.0.1
resolution: workspace
publish_to: none

environment:
  sdk: ">=3.7.2 <4.0.0"
  flutter: ">=3.29.2"

dependencies:
  flutter:
    sdk: flutter

  design_system:
    path: ../../../packages/core/design_system
  common_ui:
    path: ../../../packages/feature/common_ui
  dependency:
    path: ../../../packages/core/project_config/dependency
  localization:
    path: ../../../packages/core/project_config/localization
  domain:
    path: ../../../packages/domain
  common:
    path: ../../../packages/core/common
  injector: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
