name: quranpro
publish_to: none
environment:
  sdk: ">=3.7.2 <4.0.0"

workspace:
  - packages/core/design_system
  - packages/core/network
  - packages/core/di
  - packages/core/local_storage
  - packages/core/common
  - packages/core/core_provider
  - packages/domain
  - packages/data
  - packages/core/project_config/dependency
  - packages/core/project_config/localization
  - packages/core/project_config/config
  - packages/feature/common_ui
  - packages/feature/home

dev_dependencies:
  melos: ^7.0.0-dev.3

#
melos:
  packages:
    - packages/**

  scripts:
    generate:
      run: melos exec -c 1 "dart run build_runner build --delete-conflicting-outputs"
      packageFilters:
        dependsOn:
          - "build_runner"
    generate:adapter:
      run: melos exec -c 1 "dart run build_runner build"
      packageFilters:
        dependsOn:
          - "hive_generator"
          
    pre_build:
      run: melos run generate

  command:
    bootstrap:
      environment:
        sdk: ">=3.7.2 <4.0.0"
        flutter: ">=3.29.2"
      dependencies:
        equatable: ^2.0.5
        envied: ^1.1.1
        injector: ^4.0.0
        intl: 0.19.0

      dev_dependencies:
        build_runner: ^2.4.15
        envied_generator: ^1.1.1
        flutter_lints: ^5.0.0
        injectable_generator: ^2.7.0
        mocktail: ^1.0.4
        hive_test: ^1.0.1
        hive_generator: ^2.0.1
