name: core_provider
description: "A new Flutter package project."
version: 0.0.1
resolution: workspace
publish_to: none

environment:
  sdk: ">=3.7.2 <4.0.0"
  flutter: ">=3.29.2"

dependencies:
  flutter:
    sdk: flutter
  dependency:
    path: ../../../packages/core/project_config/dependency
  config:
    path: ../../../packages/core/project_config/config
  localization:
    path: ../../../packages/core/project_config/localization
  home:
    path: ../../../packages/feature/home
  domain:
    path: ../../../packages/domain
  data:
    path: ../../../packages/data
  local_storage:
    path: ../../../packages/core/local_storage
  injector: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0