name: di
description: "A new Flutter package project."
version: 0.0.1
resolution: workspace
publish_to: none

environment:
  sdk: ">=3.7.2 <4.0.0"
  flutter: ">=3.29.2"

dependencies:
  flutter:
    sdk: flutter
  dependency:
    path: ../../../packages/core/project_config/dependency

  localization:
    path: ../../../packages/core/project_config/localization

  network:
    path: ../../../packages/core/network

  local_storage:
    path: ../../../packages/core/local_storage

  data:
    path: ../../../packages/data

  home:
    path: ../../../packages/feature/home

  domain:
    path: ../../../packages/domain

  injector: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
